<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Password Reset Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are the default lines which match reasons
    | that are given by the password broker for a password update attempt
    | outcome such as failure due to an invalid password / reset token.
    |
    */

    'reset' => 'Password updated successfully.',
    'sent' => 'A password recovery code has been sent to your email.',
    'throttled' => 'Please wait before retrying.',
    'token' => 'This password reset token is invalid.',
    'user' => "We can't find a user with that email address.",
    'code_sent' => 'A password recovery code has been sent to your email.',
    'invalid_code' => 'The code is invalid or has expired.',
    'incorrect_code' => 'The entered code is incorrect.',
    'code_expired' => 'The code has expired. Please request a new one.',

    // Email Template Translations
    'mail_subject' => 'Password Reset Code',
    'mail_header_subtitle' => 'Account Security',
    'mail_greeting' => 'Hello, :name:',
    'mail_greeting_general' => 'Hello:',
    'mail_intro' => 'We received a request to reset your account password for :app. Use the following 6-digit verification code to complete the process:',
    'mail_code_label' => 'Your security code',
    'mail_expiration' => 'This code will expire in <strong>:minutes minutes</strong>. If you do not use it within this time, you must request a new one.',
    'mail_security_title' => "Didn't request this change?",
    'mail_security_text' => 'If you did not make this request, you can safely ignore this email. Your current password will remain unchanged.',
    'mail_footer_automated' => 'This is an automated email generated by the system. Please do not reply to this message.',
    'mail_all_rights_reserved' => 'All rights reserved.',

];
