<?php

declare(strict_types=1);

return [
    'code_sent' => 'A verification code has been sent to your email.',
    'verified' => 'Email verified successfully.',
    'incorrect_code' => 'The entered code is incorrect.',
    'code_expired' => 'The verification code has expired. Please request a new one.',
    'too_many_attempts' => 'Too many incorrect attempts. Please request a new code.',
    'not_verified' => 'You must verify your email before logging in.',
    'already_verified' => 'Your email is already verified.',

    // Email Template Translations
    'mail_subject' => 'Email Verification Code',
    'mail_header_subtitle' => 'Email Verification',
    'mail_greeting' => 'Hello, :name:',
    'mail_greeting_general' => 'Hello:',
    'mail_intro' => 'Welcome to :app! Use the following 6-digit code to verify your email address:',
    'mail_code_label' => 'Your verification code',
    'mail_expiration' => 'This code will expire in <strong>:minutes minutes</strong>. If you do not use it within this time, you must request a new one.',
    'mail_security_title' => "Didn't create an account?",
    'mail_security_text' => 'If you did not create an account, you can safely ignore this email.',
    'mail_footer_automated' => 'This is an automated email generated by the system. Please do not reply to this message.',
    'mail_all_rights_reserved' => 'All rights reserved.',
];
