name: CI/CD - Fix Code Style

on:
    push:
    pull_request:

# Stop concurrent runs of the same workflow on the same branch to prevent conflicts and redundant deployments
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    lint:
        name: Fix Code Style
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.4]
        steps:
            - name: Checkout code
              uses: actions/checkout@v5
              with:
                ref: ${{ github.head_ref || github.ref }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                tools: pint
            
            - name: Run Pint
              run: pint
            
            - name: Commit linted files
              id: auto-commit
              uses: stefanzweifel/git-auto-commit-action@v6
              with:
                commit_message: "chore: fix code style with Laravel Pint"